# Generated by Django 5.2.7 on 2026-05-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactmessage'),
        ('service', '0004_seed_service_icons'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('bio', models.TextField()),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('services', models.ManyToManyField(related_name='expert_applications', to='service.servicetype')),
            ],
            options={
                'verbose_name': 'Expert Application',
                'verbose_name_plural': 'Expert Applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
