# Generated by Django 5.2.7 on 2026-05-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_expertapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertapplication',
            name='document',
            field=models.FileField(blank=True, help_text='Upload your CV, certifications, or any supporting credential documents (PDF, DOC, DOCX, JPG, PNG — max 10 MB).', null=True, upload_to='expert_applications/documents/%Y/%m/'),
        ),
    ]
