# Generated by Django 5.2.7 on 2026-05-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_expertapplication_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=120)),
                ('donor_email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.TextField(blank=True)),
                ('stripe_session_id', models.CharField(blank=True, max_length=200)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-donated_at'],
            },
        ),
    ]
