# Generated by Django 5.2.7 on 2026-05-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulelesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Optional uploaded lesson video file.', null=True, upload_to='women/courses/videos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='modulelesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional external video link (e.g., YouTube). You can also upload a video file below.'),
        ),
    ]
