# Generated by Django 5.2.7 on 2026-05-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_modulelesson_video_file_alter_modulelesson_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
    ]
