# Generated by Django 5.2.7 on 2026-05-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_remove_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Course fee in BDT. Leave as 0 for free courses.', max_digits=10),
        ),
        migrations.AddField(
            model_name='course',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='Stripe Product ID for this course.', max_length=200),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
