# Generated by Django 5.2.7 on 2026-05-07 17:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addiction_type', models.CharField(choices=[('alcohol', 'Alcohol'), ('opioids', 'Opioids / Heroin'), ('stimulants', 'Stimulants (Cocaine, Meth)'), ('cannabis', 'Cannabis / Marijuana'), ('prescription', 'Prescription Drugs'), ('tobacco', 'Tobacco / Nicotine'), ('gambling', 'Gambling'), ('other', 'Other')], max_length=20)),
                ('program_start_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('discharged', 'Discharged')], default='active', max_length=20)),
                ('rehab_center', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselor_patients', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Profile',
                'verbose_name_plural': 'Patient Profiles',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('milestone_type', models.CharField(choices=[('days_clean', 'Days Clean'), ('goal_achieved', 'Goal Achieved'), ('program_stage', 'Program Stage'), ('custom', 'Custom')], default='days_clean', max_length=20)),
                ('target_days', models.IntegerField(blank=True, null=True)),
                ('achieved_date', models.DateField(blank=True, null=True)),
                ('is_achieved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='recovery.patientprofile')),
            ],
            options={
                'verbose_name': 'Milestone',
                'ordering': ['target_days', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CounselingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('session_time', models.TimeField()),
                ('session_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group'), ('family', 'Family'), ('online', 'Online / Telehealth')], default='individual', max_length=20)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('topics_discussed', models.TextField()),
                ('counselor_notes', models.TextField(blank=True)),
                ('patient_feedback', models.TextField(blank=True)),
                ('homework', models.TextField(blank=True, help_text='Tasks assigned to the patient')),
                ('next_session_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counselor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_sessions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='recovery.patientprofile')),
            ],
            options={
                'verbose_name': 'Counseling Session',
                'ordering': ['-session_date', '-session_time'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('appointment_type', models.CharField(choices=[('counseling', 'Counseling Session'), ('medical', 'Medical Check-up'), ('group', 'Group Session'), ('follow_up', 'Follow-up'), ('intake', 'Intake Assessment'), ('other', 'Other')], default='counseling', max_length=20)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('missed', 'Missed'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='recovery.patientprofile')),
            ],
            options={
                'verbose_name': 'Appointment',
                'ordering': ['appointment_date', 'appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_term_goals', models.TextField()),
                ('long_term_goals', models.TextField()),
                ('strategies', models.TextField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('revised', 'Revised'), ('on_hold', 'On Hold')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='recovery.patientprofile')),
            ],
            options={
                'verbose_name': 'Recovery Plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RelapseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('substance', models.CharField(max_length=100)),
                ('trigger', models.TextField()),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20)),
                ('duration', models.CharField(blank=True, help_text='e.g. 2 hours, 1 day', max_length=100)),
                ('support_received', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relapses', to='recovery.patientprofile')),
            ],
            options={
                'verbose_name': 'Relapse Record',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('mood', models.IntegerField(choices=[(1, 'Very Bad 😞'), (2, 'Bad 😔'), (3, 'Okay 😐'), (4, 'Good 😊'), (5, 'Excellent 😄')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('craving_level', models.IntegerField(help_text='Scale 1–10 (1 = minimal, 10 = severe)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('used_substance', models.BooleanField(default=False)),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('exercise_done', models.BooleanField(default=False)),
                ('trigger_avoided', models.BooleanField(default=False)),
                ('support_used', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='recovery.patientprofile')),
            ],
            options={
                'verbose_name': 'Daily Check-In',
                'ordering': ['-date'],
                'unique_together': {('patient', 'date')},
            },
        ),
    ]
