# Generated by Django 5.2.7 on 2026-05-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionupdate',
            name='status',
        ),
    ]
