# Generated by Django 5.2.7 on 2025-10-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('recovery_support', 'Recovery & Addiction Support'), ('mental_health', 'Mental Health Assistance'), ('cyber_safety', 'Cyber Safety & Online Harassment'), ('emergency_crisis', 'Emergency/Crisis Intervention'), ('account_privacy', 'Account & Privacy Issues'), ('technical', 'Technical Problems'), ('resources', 'Resources & Information Request'), ('community', 'Community & Group Support'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
