# Generated by Django 5.2.7 on 2026-05-07 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def approve_existing_published_posts(apps, schema_editor):
    BlogPost = apps.get_model('blog', 'BlogPost')
    BlogPost.objects.filter(status='published').update(is_approved=True)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpost_tags_delete_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this category as featured in community sidebar'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Post is publicly visible only after staff/admin approval'),
        ),
        migrations.RunPython(approve_existing_published_posts, migrations.RunPython.noop),
    ]
