# Generated by Django 5.2.7 on 2026-05-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_seed_service_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='icon_class',
            field=models.CharField(default='fa-user-shield', max_length=60),
        ),
    ]
