# Generated by Django 5.2.7 on 2026-05-10 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyCareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('parent_full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('child_name', models.CharField(max_length=120)),
                ('child_age_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('care_shift', models.CharField(choices=[('full_day', 'Full Day'), ('half_day', 'Half Day'), ('hourly', 'Hourly')], default='full_day', max_length=20)),
                ('care_requirements', models.TextField(help_text='Mention food preference, nap routine, allergies, and special support needs.')),
                ('preferred_start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('visit_scheduled', 'Visit Scheduled'), ('waitlisted', 'Waitlisted'), ('enrolled', 'Enrolled'), ('active', 'Active Day Care'), ('closed', 'Closed')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baby_care_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BabyCareUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('is_visible_to_parent', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('care_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='babycare.babycarerequest')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baby_care_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
