# Generated by Django 5.2.7 on 2026-05-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('expert', 'Expert'), ('admin', 'Admin')], default='client', max_length=20),
        ),
    ]
